#! /bin/sh

# exec $HOME/scripts/bash/autostart.sh &
#exec $HOME/scripts/bash/wallpaper_automation.sh &


gap=20
#PANEL_HEIGHT=25
export gap
#export PANEL_HEIGHT

#killall compton &
#killall picom -q && sleep 1 &
killall polybar -q &
picom &
compton --backend glx --paint-on-overlay --vsync opengl-swc &
sxhkd &
clipit &
#kitty &
telegram-desktop &
#viber &

bspc monitor -d 1 2 3 4 5 6 7 8 9     

dwall -s=mojave &


#	██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#	██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#	██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#	██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#	██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#	╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
                                             

xsetroot -cursor_name left_ptr

sxhkd &

bspc config focused_border_color "#00fff2"
bspc config border_radius	10
bspc config border_width     3
bspc config window_gap        15
#bspc config top_padding -5
bspc config right_padding
bspc config left_padding
bspc config split_ratio         0.5
#bspc config borderless_monocle  true
bspc config gapless_monocle     false

#bspc config presel_feedback_color "#1a1a1a"

#bspc desktop ^1 -l monocle

#################       xprop | grep WM_CLASS                                                      18:29:54

bspc rule -a Pamac-manager state=floating rectangle=1100x800+410+240
bspc rule -a Pulseaudio-equalizer-gtk state=floating rectangle=800x600+560+240
bspc rule -a Pavucontrol state=floating rectangle=800x600+560+240
bspc rule -a ViberPC state=floating rectangle=1100x600+410+240
bspc rule -a TelegramDesktop state=floating node=private
#bspc rule -a Gimp desktop=^8 state=floating follow=on
#bspc rule -a Google-chrome desktop=^1
#bspc rule -a Genymotion desktop=^3
#bspc rule -a  desktop=^3
#bspc rule -a Subl desktop=^4
#bspc rule -a Spotify desktop=^5
#bspc rule -a Lmms desktop=^5
#bspc rule -a mplayer2 state=floating
#bspc rule -a Gedit state=floating
#bspc rule -a Eog state=floating
#bspc rule -a Nautilus state=floating
#bspc rule -a File-roller state=floating
#bspc rule -a Gnome-system-monitor state=floating

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
#bspc config click_to_focus true
bspc config focus_follows_pointer true

#bspc config presel_feedback_color \#aaaaaa

xsetroot -cursor_name bibata_oil
 
#feh --bg-fill ~/Pictures/red_tulips.jpg
#feh --bg-fill ~/Pictures/zF1V6EE.jpg 
#feh --randomize --bg-fill ~/Pictures/dark
#gnome-wallpaper-changer &
#xrdb -merge ~/.Xdefaults
#redshift &
#/home/gamehelp16/allfloat.sh &

#clight &
#dunst
dunst &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#panel &
bash /home/sanya/.config/polybar/launch1.sh &
bash /home/sanya/pulse.sh &
bash /home/sanya/clear.sh &

while true; do ./bat.sh; sleep 30; done &
#nitrogen --restore &
#xfce4-power-manager &
#bash hideIt.sh --name '^Polybar tray window$' --region 0x0+20+20 $
# Password for Admin
#kitty python3 /home/sanya/dynwalls/dynwalls use gora.heic &
