#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

nitrogen --restore &
gap=20
#PANEL_HEIGHT=25
export gap
#export PANEL_HEIGHT

#killall compton &
#killall picom -q && sleep 1 &
killall polybar -q &
picom &
compton --backend glx --paint-on-overlay --vsync opengl-swc &
#sxhkd &
clipit &
#kitty &
telegram-desktop &
#viber &
sleep 5 && kitty sudo fusuma -d &

bspc monitor -d 1 2 3 4 5 6 7 8 9

dwall -s=mojave &


#	██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#	██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#	██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#	██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#	██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#	╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝


xsetroot -cursor_name left_ptr

sxhkd -c /home/sanya/.config/bspwm/sxhkd/sxhkdrc &

bspc config focused_border_color "#00fff2"
bspc config border_radius	5
bspc config border_width     3

#bspc config window_gap        15

bspc subscribe node_focus | while read -a msg ; do
  desk_id=${msg[2]}
  wind_id=${msg[3]}
  if [ $(bspc query -d $desk_id -N | wc -l) -eq 1 ]; then
    bspc config -d "$desk_id" window_gap 50
    bspc config -d "$desk_id" top_padding -20
  else
    bspc config -d "$desk_id" top_padding 0
    bspc config -d "$desk_id" window_gap 5
  fi
done &


#bspc config top_padding -10
bspc config right_padding
bspc config left_padding
bspc config split_ratio         0.5
#bspc config borderless_monocle  true
bspc config gapless_monocle     false

#bspc config presel_feedback_color "#1a1a1a"

#bspc desktop ^1 -l monocle

#################       xprop | grep WM_CLASS                                           

bspc rule -a Pamac-manager state=floating rectangle=1100x800+410+240
bspc rule -a Pulseaudio-equalizer-gtk state=floating rectangle=800x600+560+240
bspc rule -a Pavucontrol state=floating rectangle=800x600+560+240
bspc rule -a ViberPC state=floating rectangle=1100x600+410+240
bspc rule -a discord state=floating 
bspc rule -a TelegramDesktop state=floating node=private
#bspc rule -a Gimp desktop=^8 state=floating follow=on
#bspc rule -a Google-chrome desktop=^1
#bspc rule -a Genymotion desktop=^3
#bspc rule -a  desktop=^3
#bspc rule -a Subl desktop=^4
#bspc rule -a Spotify desktop=^5
#bspc rule -a Lmms desktop=^5
#bspc rule -a mplayer2 state=floating
#bspc rule -a Gedit state=floating
#bspc rule -a Eog state=floating
#bspc rule -a Nautilus state=floating
#bspc rule -a File-roller state=floating
#bspc rule -a Gnome-system-monitor state=floating

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
#bspc config click_to_focus true
bspc config focus_follows_pointer true

#bspc config presel_feedback_color \#aaaaaa

xsetroot -cursor_name bibata_oil

#feh --bg-fill ~/Pictures/red_tulips.jpg
#feh --bg-fill ~/Pictures/zF1V6EE.jpg
#feh --randomize --bg-fill ~/Pictures/dark
#gnome-wallpaper-changer &
#xrdb -merge ~/.Xdefaults
#redshift &
#/home/gamehelp16/allfloat.sh &

#clight &
#dunst
dunst &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#panel &
bash /home/sanya/.config/polybar/launch1.sh &
bash /home/sanya/pulse.sh &
bash /home/sanya/clear.sh &

while true; do ./bat.sh; sleep 30; done &

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10

#Fullscreen applications
bspc rule -a inkscape state=fullscreen
bspc rule -a Spotify state=fullscreen
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
#bspc rule -a Gimp state=fullscreen

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a Arcolinux-tweak-tool.py state=floating
bspc rule -a Arcolinux-welcome-app.py state=floating
bspc rule -a feh state=floating
#bspc rule -a mpv state=floating sticky=on
#bspc rule -a Font-manager state=floating
bspc rule -a Galculator state=floating
#bspc rule -a Gpick state=floating sticky=on
#bspc rule -a Nitrogen state=floating
bspc rule -a Oblogout state=floating
#bspc rule -a Pavucontrol state=floating sticky=on
#bspc rule -a Peek state=floating
#bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating
#bspc rule -a Stacer state=floating
#bspc rule -a Xfce4-appfinder state=floating sticky=on
bspc rule -a Xfce4-terminal state=floating

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

#open applications on specific workspaces
#bspc rule -a Firefox desktop='^1' follow=on
#bspc rule -a Google-chrome desktop='^1' follow=on
#bspc rule -a Chromium desktop='^1'  follow=on
#bspc rule -a Subl3 desktop='^2' follow=on
#bspc rule -a Atom desktop='^2' follow=on
#bspc rule -a Steam desktop='^5'
#bspc rule -a vlc desktop='^6'  follow=on
#bspc rule -a mpv desktop='^6'  follow=on
#bspc rule -a Vivaldi-stable desktop='^6' follow=on
#bspc rule -a Vivaldi-snapshot desktop='^6' follow=on
#bspc rule -a Transmission-gtk desktop='^7' follow=on
#bspc rule -a Thunar desktop='^8' follow=on
#bspc rule -a discord desktop='^9' follow=on
#bspc rule -a Spotify desktop='^10' follow=on

#Spotify fix  --move desktop 10
#sleep 1
#wmctrl -r Spotify -t 10
#exit

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
